### ISSUE TITLE
Use revision numbers instead of version numbers for updating apps

### ISSUE THREAD

**Issue by bhdouglass** [UbuntuOpenStore/openstore-meta#109]
https://github.com/UbuntuOpenStore/openstore-web/issues/12

See title. Some developers prefer to just submit smaller changes to their apps without changing the version number (and only change the version number for big changes). With this, the App does not get shown as outdated/updatable.

**Comment by bhdouglass** [comment]
done!

**Comment by bhdouglass** [comment]
(the app needs to be updated, but the backend support is all there.

**Comment by NeoTheThird** [comment]
Where exactly does the revision number come from?

**Comment by bhdouglass** [comment]
The revision number is basically an internal version number that the OpenStore tracks.

**Comment by NeoTheThird** [comment]
Ok! That makes sense. Sorry about the confusion, i was just a little traumatized with all the coreapps that run `bzr revno` to figure out the version number (bazaar revision number) when building. But this sounds like a good system! Thanks!

**Comment by bhdouglass** [comment]
Haha no worries. We just borrowed the concept from the Canonical's store.
