### ISSUE TITLE
Aopen store will not install

### ISSUE THREAD

**Issue by prpldvl67** [UbuntuOpenStore/openstore-meta#112]
Hi On Mpkcon install-local --allow-untrusted openstore.openstore-team_0.103_armhf.click FHD 

I keep getting such error: fatal error: coul not resolve .openstore.openstore-team_0.103_armhf.click

**Comment by bhdouglass** [comment]
It looks like you have an old version of the openstore, try using the latest version: https://open.uappexplorer.com/docs#install

**Comment by bhdouglass** [comment]
I'm closing this since there hasn't been an update in a while. If you are still having issues feel free to reopen this issue.
