### ISSUE TITLE
Openstore stuck with updating itself

### ISSUE THREAD

**Issue by Flohack74** [UbuntuOpenStore/openstore-meta#114]
First time this happens, no progress possible anymore:
![screenshot20170605_153347878](https://cloud.githubusercontent.com/assets/16186470/26786047/7af6d4fe-4a05-11e7-9e65-b49e862cc456.png)

After closing / restarting it installed instantly.

**Comment by bhdouglass** [comment]
@Flohack74 can you upload your logs for the openstore?

**Comment by Flohack74** [comment]
[openstore-log.txt](https://github.com/UbuntuOpenStore/openstore-meta/files/1052204/openstore-log.txt)

**Comment by bhdouglass** [comment]
@sverzegnassi any idea what's going on? It looks like it installs fine.

**Comment by Flohack74** [comment]
You can see in the log, the first try was unsuccessful.. but no error msgs

**Comment by sverzegnassi** [comment]
The only strange thing I see is at line 23 and following. OpenStore started to download the package but never finished it.

@Flohack74 I see you attached the screenshot of OpenStore failing to download the package.
Could you please tell me which was the status of the progress bar? Usually:

1. At first it shows a cyclic animation (i.e. indeterminate state) when connecting to the server
2. It exits the indeterminate state and shows the progress of the download
3. It enters the indeterminate state again during installation of the .click package

The only evidence I can take from the log is that the installation never reached the third step. Could you please give me a bit of context?

**Comment by sverzegnassi** [comment]
Anyway, I don't see any hint that suggests this happened because OpenStore was trying to update itself.
It looks like this issue could be triggered with any of the apps available in the store.

**Comment by Flohack74** [comment]
Lets close it for the time being, never happened again...
