### ISSUE TITLE
[app][v1.01][E5] Warning text gets cut

### ISSUE THREAD

**Issue by cibersheep** [UbuntuOpenStore/openstore-meta#122]
![imatge](https://user-images.githubusercontent.com/6640041/27149410-c3fbcd4a-5143-11e7-9cc3-b9b948c8a861.png)

![imatge](https://user-images.githubusercontent.com/6640041/27149391-afb9984e-5143-11e7-8c5b-d902002a2fe1.png)

**Comment by sverzegnassi** [comment]
Fixed in v.2.00 (now merged into master)
