### ISSUE TITLE
Icons for categories

### ISSUE THREAD

**Issue by mivoligo** [UbuntuOpenStore/openstore-meta#123]
It would be nice visual improvement if each category had its own icon. I understand we need some changes in the API to be able to do that. Personally I can find and/or design appropriate icons.

**Comment by bhdouglass** [comment]
I just added support for this, I just need some icons: https://github.com/UbuntuOpenStore/openstore-web/blob/master/api/app/category_icons.json

If you find/design some icons, just let me know and I'll include them!

**Comment by mivoligo** [comment]
Zipped icons

[categories-icons.zip](https://github.com/UbuntuOpenStore/openstore-meta/files/1088171/categories-icons.zip)

**Comment by bhdouglass** [comment]
Awesome! Thanks!
