### ISSUE TITLE
Namespace protection for core Apps

### ISSUE THREAD

**Issue by Flohack74** [UbuntuOpenStore/openstore-meta#124]
Currently it would be possible to upload any App in the "com.ubuntu.*" or "com.ubports.*" namespace, which we should avoid. As long as we have not moved all core Apps the namespaces are free to claim, and this could cause mistakes or confusion (even if someone just wants to help and starts uploading). A protection for "our" namespaces would be nice.

**Comment by bhdouglass** [comment]
Just uploaded an updated for this!
