### ISSUE TITLE
'Discover' endpoint should return package details

### ISSUE THREAD

**Issue by sverzegnassi** [UbuntuOpenStore/openstore-meta#125]
Currently the 'Discover' endpoint returns a list of package IDs. We've found this approach acceptable since we previously download the full list of applications from the server.

We're currently moving the client-app to use the latest OpenStore APIs which provides full support for pagination. This is a necessary step for improving client-app performance, since downloading 300+ package details at start-up is not a reasonable approach anymore. However this affects our support for the Discover API.

What we would need now is to make 'Discover' endpoint return a list of "package details" (i.e. the way 'apps' API works), rather than returning IDs only.

**Comment by bhdouglass** [comment]
Done!
