### ISSUE TITLE
OpenStore app description, '<' and '>' will be ignored

### ISSUE THREAD

**Issue by TronFourtyTwo** [UbuntuOpenStore/openstore-meta#126]
To reproduce:
Go in open.uappexplorer.com/manage and open an app settings. Change description adding for example `<test>`, then press update.
You will see `<test>` hasn't been added to the description.

**Comment by bhdouglass** [comment]
This is happening because we strip out any html tags. I'll see about trying to preserve them as `&gt;` & `&lt;`

**Comment by bhdouglass** [comment]
@TronFourtyTwo can you explain your usage here? I'm not seeing a compelling reason to change what we currently have (we are currently stripping any and all html tags from the description to prevent nasty stuff).

**Comment by TronFourtyTwo** [comment]
Oh, no reason. I just saw a thing which I thought it was a bug and reported it.

**Comment by bhdouglass** [comment]
Ok, then I'm just going to close this out as I don't want to circumvent the html cleanup.
