### ISSUE TITLE
Missing details in web "Development" steps 

### ISSUE THREAD

**Issue by doniks** [UbuntuOpenStore/openstore-meta#127]
I'm trying to get through the steps here:

https://github.com/UbuntuOpenStore/openstore-web#development

but I think I'm missing some details. I get to the point where I browse to http://local.open.uappexplorer.com/ but the only answer I get is 502 Bad Gateway.

I did:
git clone
vagrant plugin install vagrant-docker-compose
vagrant up 
npm install
firefox 192.168.58.123 
-> bad gateway 

vagrant ssh
attach_api
-> this spews out errors forever like: 
```
Program node index.js exited with code 1

Starting child process with 'node index.js'
module.js:341
    throw err;
    ^

Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/openstore/api/utils/logger.js:2:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
module.js:341
    throw err;
    ^
```

docker ps
->
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
39f1f6424be4        openstore_api       "npm run dev"            14 minutes ago      Up 14 minutes       0.0.0.0:8080->8080/tcp     openstore_api_1
b8b72771ecaf        mongo               "docker-entrypoint..."   14 minutes ago      Up 14 minutes       0.0.0.0:27017->27017/tcp   openstore_mongo_1
```
Sooo, maybe openstore_api IS already attached?!

```
vagrant@openstore:/srv/openstore$ attach_web 
You cannot attach to a stopped container, start it first
vagrant@openstore:/srv/openstore$ docker start openstore_web_1
openstore_web_1
vagrant@openstore:/srv/openstore$ attach_web 
You cannot attach to a stopped container, start it first
vagrant@openstore:/srv/openstore$ 
```

Not quite sure what I'm doing wrong. I'm new to any of vagrant, docker, npm. Any help would be appreciated.

**Comment by bhdouglass** [comment]
It seems those instructions are out of date! I split the dependencies of the api and the web app, so the steps have changed. I've updated the README file, let me know if that works!

**Comment by doniks** [comment]
Brings me up to a different error:

```
$ vagrant ssh # I'm assuming that's what I should do according to "(it's best to run this in the VM)"
vagrant@openstore:/srv/openstore$ cd api
vagrant@openstore:/srv/openstore/api$ npm install
The program 'npm' is currently not installed. To run 'npm' please ask your administrator to install the package 'npm'
vagrant@openstore:/srv/openstore/api$ sudo apt install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
[...]
Setting up node-sha (1.2.3-1) ...
Setting up node-slide (1.1.4-1) ...
Setting up npm (1.3.10~dfsg-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
vagrant@openstore:/srv/openstore/api$ npm install         
npm WARN package.json openappstore-api@1.0.0 No description
npm WARN package.json openappstore-api@1.0.0 No README data
npm http GET https://registry.npmjs.org/bytes/-/bytes-2.2.0.tgz
npm http GET https://registry.npmjs.org/camelcase/-/camelcase-3.0.0.tgz
[...]
npm http GET https://registry.npmjs.org/read-chunk/-/read-chunk-1.0.1.tgz
npm http 200 https://registry.npmjs.org/es6-promise/-/es6-promise-3.3.1.tgz
npm http 200 https://registry.npmjs.org/read-chunk/-/read-chunk-1.0.1.tgz

> squashfs-nodejs@1.0.6 install /srv/openstore/api/node_modules/squashfs-nodejs
> cd lib/squashfs-nodejs && node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-121-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /srv/openstore/api/node_modules/squashfs-nodejs/lib/squashfs-nodejs
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by bhdouglass** [comment]
Ah ok, it should be run inside the docker container, I'll post another update later.

**Comment by bhdouglass** [comment]
Ok, new update. I've gone through the steps myself and it seems to be working fine. You'll have to start fresh though, so you'll want to do a `vagrant destroy` then follow the instructions again. Let me know if that works for you!

**Comment by doniks** [comment]
Another attempt another error :(

Started fresh on a new Ubuntu 17.04 installation (previous attempts were 16.04)

git clone https://github.com/UbuntuOpenStore/openstore-web
sudo apt install vagrant
sudo apt install virtualbox
vagrant plugin install vagrant-docker-compose
vagrant up


==> default: npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
==> default: npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
==> default: npm WARN openappstore-web@1.0.0 No description
==> default: npm WARN openappstore-web@1.0.0 No repository field.
==> default: npm WARN openappstore-web@1.0.0 scripts['server'] should probably be scripts['start'].
==> default: npm ERR! Linux 3.13.0-123-generic
==> default: npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
==> default: npm ERR! node v5.11.1
==> default: npm ERR! npm  v3.8.6
==> default: npm ERR! path /srv/openstore/www/node_modules/esprima/bin/esparse.js
==> default: npm ERR! code ENOENT
==> default: npm ERR! errno -2
==> default: npm ERR! syscall chmod
==> default: 
==> default: npm ERR! enoent ENOENT: no such file or directory, chmod '/srv/openstore/www/node_modules/esprima/bin/esparse.js'
==> default: npm ERR! enoent ENOENT: no such file or directory, chmod '/srv/openstore/www/node_modules/esprima/bin/esparse.js'
==> default: npm ERR! enoent This is most likely not a problem with npm itself
==> default: npm ERR! enoent and is related to npm not being able to find a file.
==> default: npm ERR! enoent 
==> default: 
==> default: npm ERR! Please include the following file with any support request:
==> default: npm ERR!     /srv/openstore/www/npm-debug.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I proceeded anyway, but now my notes are a bit more fuzzy, I went through a few attemps of

vagrant ssh
attach_api
sits there forever without ending and without any output

second shell:
vagrant ssh
attach_web
same error as before about you cannot attach

vagrant halt

try again, 

vagrant up
vagrant ssh
attach_api
sits there

second shell
vagrant ssh
attach_web
now this one is also sitting there quite

browsing to the IP now doesn't give a gateway error, now it says "The connection has timed out" after a while

docker logs look as follows:


docker logs openstore_api_1 
npm info it worked if it ends with ok
npm info using npm@3.8.6
npm info using node@v5.11.1
npm info lifecycle openstore@1.0.0~predev: openstore@1.0.0
npm info lifecycle openstore@1.0.0~dev: openstore@1.0.0

> openstore@1.0.0 dev /srv/openstore
> cd api && npm run dev

npm info it worked if it ends with ok
npm info using npm@3.8.6
npm info using node@v5.11.1
npm info lifecycle openappstore-api@1.0.0~predev: openappstore-api@1.0.0
npm info lifecycle openappstore-api@1.0.0~dev: openappstore-api@1.0.0

> openappstore-api@1.0.0 dev /srv/openstore/api
> supervisor -V -w app,db,utils,index.js index.js


Running node-supervisor with
  program 'index.js'
  --watch 'app,db,utils,index.js'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node index.js'
Watching directory '/srv/openstore/api/app' for changes.
Press rs for restarting the process.
Watching directory '/srv/openstore/api/db' for changes.
Press rs for restarting the process.
Watching directory '/srv/openstore/api/utils' for changes.
Press rs for restarting the process.
Watching directory '/srv/openstore/api/index.js' for changes.
Press rs for restarting the process.
watching file '/srv/openstore/api/index.js'
watching file '/srv/openstore/api/app/apps.js'
watching file '/srv/openstore/api/app/auth.js'
watching file '/srv/openstore/api/app/categories.js'
watching file '/srv/openstore/api/app/helpers.js'
watching file '/srv/openstore/api/app/index.js'
watching file '/srv/openstore/api/app/upload.js'
watching file '/srv/openstore/api/app/users.js'
watching file '/srv/openstore/api/db/index.js'
watching file '/srv/openstore/api/utils/checksum.js'
watching file '/srv/openstore/api/app/snaps.js'
watching file '/srv/openstore/api/utils/click-parser-async.js'
watching file '/srv/openstore/api/utils/config.js'
watching file '/srv/openstore/api/utils/opengraph.js'
watching file '/srv/openstore/api/utils/logger.js'
watching file '/srv/openstore/api/utils/packages.js'
watching file '/srv/openstore/api/utils/review-package.js'
debug:   No papertrail token
debug:   spawning 1 processes
debug:   No papertrail token
error:   uncaughtException: TypeError: OAuth2Strategy requires a clientID option
error:   TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/srv/openstore/api/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/srv/openstore/api/node_modules/passport-github/lib/strategy.js:62:18)
    at Object.setup (/srv/openstore/api/app/auth.js:127:18)
    at Object.setup (/srv/openstore/api/app/index.js:25:10)
    at Object.<anonymous> (/srv/openstore/api/index.js:27:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3




docker logs openstore_web_1 
npm info it worked if it ends with ok
npm info using npm@3.8.6
npm info using node@v5.11.1
npm info lifecycle openstore@1.0.0~prewebpack-dev: openstore@1.0.0
npm info lifecycle openstore@1.0.0~webpack-dev: openstore@1.0.0

> openstore@1.0.0 webpack-dev /srv/openstore
> cd www && npm run devserver

npm info it worked if it ends with ok
npm info using npm@3.8.6
npm info using node@v5.11.1
npm info lifecycle openappstore-web@1.0.0~predevserver: openappstore-web@1.0.0
npm info lifecycle openappstore-web@1.0.0~devserver: openappstore-web@1.0.0

> openappstore-web@1.0.0 devserver /srv/openstore/www
> webpack-dev-server --progress --colors -d --host 0.0.0.0 --watch-poll


Project is running at http://0.0.0.0:8081/
webpack output is served from /
404s will fallback to /index.html
 20% building modules 85/108 modules 23 acwebpack: Failed to compile.ceiver/htmlfile.js
Hash: 84f40944b9a1ffcff9a2                                                              
Version: webpack 2.2.0
Time: 4850ms
                         Asset     Size  Chunks                    Chunk Names
bundle.9083ebb875d5ce2460d1.js  7.04 MB       0  [emitted]  [big]  main
                    index.html  4.95 kB          [emitted]         
chunk    {0} bundle.9083ebb875d5ce2460d1.js (main) 2.65 MB [entry] [rendered]
   [14] ./~/jquery/dist/jquery.js 258 kB {0} [built]
   [35] ./app.js 3.72 kB {0} [built]
   [36] (webpack)-dev-server/client?http://0.0.0.0:8081 4.66 kB {0} [built]
   [49] ./app/filters/versionFix.js 145 bytes {0} [built]
   [50] ./app/services/api.js 2.93 kB {0} [built]
   [51] ./app/services/info.js 1.71 kB {0} [built]
   [52] ./bower_components/Uploadcare/uploadcare.min.js 239 kB {0} [built]
   [53] ./bower_components/swipebox/src/js/jquery.swipebox.js 25 kB {0} [built]
   [55] ./~/angular-ui-bootstrap/index.js 71 bytes {0} [built]
   [56] ./~/angular-ui-router/release/angular-ui-router.js 173 kB {0} [built]
   [74] ./~/ng-file-upload/index.js 70 bytes {0} [built]
   [75] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
  [106] (webpack)-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
  [109] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [117] multi (webpack)-dev-server/client?http://0.0.0.0:8081 ./app.js 40 bytes {0} [built]
     + 103 hidden modules

ERROR in ./app.js
Module not found: Error: Can't resolve 'css-loader' in '/srv/openstore/www'
 @ ./app.js 20:0-25
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 ./app.js

ERROR in ./app.js
Module not found: Error: Can't resolve 'css-loader' in '/srv/openstore/www'
 @ ./app.js 21:0-26
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 ./app.js

ERROR in ./app.js
Module not found: Error: Can't resolve 'css-loader' in '/srv/openstore/www'
 @ ./app.js 19:0-63
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 ./app.js

ERROR in ./app.js
Module not found: Error: Can't resolve 'css-loader' in '/srv/openstore/www'
 @ ./app.js 16:0-62
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 ./app.js

ERROR in ./app.js
Module not found: Error: Can't resolve 'css-loader' in '/srv/openstore/www'
 @ ./app.js 17:0-68
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 ./app.js

ERROR in ./app.js
Module not found: Error: Can't resolve 'css-loader' in '/srv/openstore/www'
 @ ./app.js 18:0-63
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 ./app.js
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 546 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] (webpack)/buildin/global.js 509 bytes {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
        [3] ./~/html-webpack-plugin/lib/loader.js!./index.html 5.34 kB {0} [built]

**Comment by bhdouglass** [comment]
Ok, the problem with the api is because you don't have any credentials for the GitHub login (I do so I didn't notice any issue), so I've fixed that in my latest commit.

The problem with the website is because you're missing some dependencies, which is probably because of the first error. Try running this command from your VM: `docker exec openstore_api_1 bash -c "cd /srv/openstore/www && npm install"` and then restart the docker container by running `docker-compose restart`.

**Comment by bhdouglass** [comment]
Any luck getting the development environment setup?

**Comment by doniks** [comment]
Haven't gotten around to trying it again. I should have some time this afternoon.

**Comment by doniks** [comment]
Sorry, @bhdouglass I'm not getting to this. And realistically, I will not get to it over the next month or two and then who knows. So, if you feel like closing the issue to not have it sit around forever, just go ahead. I know where to find you when I find time to return to this :) Thanks for your help!

**Comment by bhdouglass** [comment]
I'm sorry this hasn't worked for you yet! I'll close this for now, but when you can get back to this just let me know and we can take a crack at it again.
