### ISSUE TITLE
 [app][v1.01] App looks like is not uninstalled untill reopen OpenStore

### ISSUE THREAD

**Issue by cibersheep** [UbuntuOpenStore/openstore-meta#136]
- Open app detail
- Uninstall app and wait for process to finish
- App is shown as installed
- Close and open OpenStore
- Open app details
- App is shown as uninstalled

**Comment by sverzegnassi** [comment]
Fixed in v.2.00 (now merged into master). Please let us know how it works, so that we can reopen this issue in case. :)
