### ISSUE TITLE
 [app][v1.01][enhancement] Installing external click improvement

### ISSUE THREAD

**Issue by cibersheep** [UbuntuOpenStore/openstore-meta#137]
When installing an external click with OpenStore asks permission to install and success message. It could show the % of the process.
Do you want to install this app?
![imatge](https://user-images.githubusercontent.com/6640041/29006040-8b413c6e-7ae8-11e7-8dae-23003e81a588.png)

then it show empty message, it could be used to show progress bar / % / "installing" message
![imatge](https://user-images.githubusercontent.com/6640041/29006051-b4e2f314-7ae8-11e7-8f2a-67d7b090c476.png)

**Comment by sverzegnassi** [comment]
Fixed in v.2.00 (now merged into master). Please let us know how it works, so that we can reopen this issue in case. :)
