### ISSUE TITLE
Feature request: Group Accounts

### ISSUE THREAD

**Issue by NeoTheThird** [UbuntuOpenStore/openstore-meta#142]
It would be nice to be able to publish Apps to some sort of group account. GitHub organizations could provide the OAuth login for that, so that for example everybody in the UBports GitHub organization could publish Apps under the UBports name on the OpenStore. Since you wouldn't log in with a seperate account anymore, it would be nice to selecting the available group accounts in the "Manage" view, similar to the way Travis-CI and other services using GitHub organizations differentiate between personal and shared accounts.

**Comment by bhdouglass** [comment]
9 times out of 10 isn't an app maintained by just one person? I would think it would make sense for everything to pass through that person so we don't come into a situation where the right hand doesn't know what the left hand is doing.

**Comment by NeoTheThird** [comment]
You are probably right. With #142 out of the way, it's probably not even necessary for UBports, so the only example i can think of is void :D

**Comment by sverzegnassi** [comment]
With reference to issue #143 , wouldn't make sense for UBports needs to use a Jenkins/Travis CI instance, connected via GitHub webhooks (e.g. [release](https://developer.github.com/v3/activity/events/types/#releaseevent) ), which uploads a new package using the OpenStore CLI tool? That way, members of the organization would only have to upload a new package into the GitHub repository, and everything would happen auto-magically.

I'm just thinking out loud, but it seems more straight-forward/linear to implement, and it would be feasible even with other source code repository services (e.g. Launchpad).

**Comment by bhdouglass** [comment]
I second @sverzegnassi 's idea

**Comment by NeoTheThird** [comment]
@sverzegnassi Yep, exactly. That's what i meant by this:
> With #143 out of the way, it's probably not even necessary for UBports
