### ISSUE TITLE
Feature request: Automatic Uploads

### ISSUE THREAD

**Issue by NeoTheThird** [UbuntuOpenStore/openstore-meta#143]
It would be very useful to have an exposed API to automatically upload new packages to the OpenStore. This could be nicely integrated with automatic pipelining systems like Jenkins.

**Comment by bhdouglass** [comment]
The OpenStore is split up into an api with a web client and the app talking to it, so this already done! Although it's super undocumented. For integrating it with Jenkins check out https://github.com/UbuntuOpenStore , it is a cli tool for uploading packages to the api. It's a bit old but should still work.

**Comment by NeoTheThird** [comment]
*eyes get bigger* Thanks, this is gold!

**Comment by bhdouglass** [comment]
:)
