### ISSUE TITLE
Allow packages to require a certain OTA version

### ISSUE THREAD

**Issue by NeoTheThird** [UbuntuOpenStore/openstore-meta#146]
For apps that depend on system services that are included in the system-image, it would be nice to be able to set an OTA version required for upgrade and installation.

**Comment by bhdouglass** [comment]
I don't like the idea of preventing a user from installing an app if they want to, but I understand the usecase. I would be ok with a warning or something.

**Comment by NeoTheThird** [comment]
A warning could also be enough.

**Comment by sverzegnassi** [comment]
Ubuntu Touch has always handled this through "system frameworks"[1][2], and OpenStore already supports this feature.

Canonical used to update the framework list anytime there was a change in the AppArmor permission list (e.g. new permission added) or new public APIs got added.
There is no strict rules for the naming, so you could safely create new framework like "ubports-ota-2" or "ubports-api-2".

My feeling here is that the issue report is about re-creating the same thing.

[1] i.e. "ubuntu-sdk-15.04.4" and similar
[2] https://click.readthedocs.io/en/latest/file-format.html#manifest

**Comment by NeoTheThird** [comment]
Right, i didn't think of that. Thanks @sverzegnassi! I guess this can be closed then.
