### ISSUE TITLE
Corect translation is missing

### ISSUE THREAD

**Issue by toddy** [UbuntuOpenStore/openstore-meta#147]
Hi, at my smartphone I get the string "Packetliste wird geladen“ (German) when the package list is loading at the beginn of the app. The string is wrong in German. It must be "Paketliste wird geladen" In the translation project it is correct but it seems that this is not updated till now. Can somebody update the translation for the project, so that the issue is fixed in the actual version?
Bests  Torsten

**Comment by bhdouglass** [comment]
I've just published v1.02 to the openstore, it's got the latest translations.
