### ISSUE TITLE
the search is a bit fishy

### ISSUE THREAD

**Issue by pixelr0** [UbuntuOpenStore/openstore-meta#148]
launch the openstore and search "Fishy"

"F" it returns one entry "HexGL"
"Fi" returns "no result found"
"Fis" no result
"Fish" returns 3 entries Fish Tank, Let;s go fising and Fishy Shooter

**Comment by Flohack74** [comment]
Also: Search for Wifi does not return wifiscanner app ;)

**Comment by bhdouglass** [comment]
Yeah the search functionality isn't as good as what I have setup for uApp Explorer. I'll have implement that same functionality here. In the meantime the app's author should add some keywords for better discovery.

**Comment by bhdouglass** [comment]
This has been fixed on the website and the app will receive an update "soon" (#169) for this as well.
