### ISSUE TITLE
Simplified Chinese translation is missing

### ISSUE THREAD

**Issue by mutse** [UbuntuOpenStore/openstore-meta#155]
Hi, at my smart phone Nexus 5, openstore-app does not show Simplified Chinese translation.  I find that there is zh_Hans.po in the openstore-app project, and then I rename it as zh_CN.po, Simplified Chinese translation works.

**Comment by bhdouglass** [comment]
@sverzegnassi do you know anything about this? The translations are coming from weblate, so this could be a problem on their end.

**Comment by sverzegnassi** [comment]
I don't know how the translation infrastructure is set up for OpenStore, but I guess Florian knows. I'll try to ping him :)

**Comment by Flohack74** [comment]
yes indeed smth is wrong with the po file. @bhdouglass can you rename zh_hans in the repo? Then weblate can pick it up, too.

Chinese po files should follow this convention probably:
![grafik](https://user-images.githubusercontent.com/16186470/30986160-cbfcf0c6-a492-11e7-9c9c-df3ca93e9af7.png)

**Comment by bhdouglass** [comment]
Ok, I just pushed that change, lets see how weblate handles it.

**Comment by Flohack74** [comment]
Its ok now, also Weblate picked up the new file. Note, in Weblate its still zh_hans, but it links to the correct po: https://translate.ubports.com/projects/openstore/openstore-app/zh_Hans/

**Comment by bhdouglass** [comment]
thanks @Flohack74 !
