### ISSUE TITLE
Verify and sign clicks

### ISSUE THREAD

**Issue by mardy** [UbuntuOpenStore/openstore-meta#157]
When a new click is uploaded, the store should run the same checks that the Ubuntu Store used to run and, if they pass, it should sign the click and set a flag on them.

Then, the `api/v1/apps` endpoint should accept a query parameter `signed_only=1` that, if set will filter out all unsigned apps.

**Comment by bhdouglass** [comment]
We are already running each app through the same automated review process that the old Ubuntu Store used. But I'm not sure what the point of signing them is? And if we did we should probably do it to all apps so the query parameter would be unnecessary.

**Comment by mardy** [comment]
My suggestion is to sign only those which have passed the security check. The verification tool was emitting some errors if the app was unconfined or if it was using some not allowed policies.

**Comment by bhdouglass** [comment]
Half the point of the OpenStore is having the unconfined and restricted permissions apps. So not signing them doesn't make a whole lot of sense.

**Comment by mardy** [comment]
It makes sense on the client side, because the pkcon tool refuses to install unsigned packages unless it's given the `--allow-unauthenticated` flag. So, by signing some apps and not others, you are giving users (those who want it) the certainty that it) the apps they are installing are confined.
This would be unnecessary if the Ubuntu store were still fully functionalfunctional. But since it isn't, my suggestion is that the Openstore could replicate its functionality.

**Comment by bhdouglass** [comment]
All apps in the OpenStore come with a section detailing which permissions they require and unconfined ones (and other "restricted" permissions) show in red to let the user know what they are getting. I don't think we should be hiding some amazing apps (like the Ubuntu touch tweak tool and the file manager to name a few) just because they need privileges beyond those afforded to them by confinement.

**Comment by mardy** [comment]
Mmm... Then I guess you are right, no need to discriminate based on the signature.
So, do consider this bug report as a request to sign all clicks :-)

**Comment by mardy** [comment]
Ah, you've caught me! I don't know :-) I know that pkcon uses `debsig-verify` to verify the signature. I'll investigate.

**Comment by bhdouglass** [comment]
Thanks! I don't have a problem trying to implement this if it makes installing apps less "scary".

**Comment by bhdouglass** [comment]
@mardy did you ever figure out how to properly sign the packages?

**Comment by mardy** [comment]
Sorry no, I didn't spend time on this :-(

**Comment by bhdouglass** [comment]
Ok, thanks, I'm going to close out this issue for now.
