### ISSUE TITLE
Cannot test the openstore in vagrant

### ISSUE THREAD

**Issue by mardy** [UbuntuOpenStore/openstore-meta#158]
Hi,
  i"m having some trouble running the openstore in vagrant. I've followed the README till the `vagrant up` command, but then the attach_* methods fail: the `attach_api` never returns, and the other one results in
```
vagrant@openstore:/srv/openstore$ attach_web 
You cannot attach to a stopped container, start it first
```
If it can help, here's my docker containers:
```
vagrant@openstore:/srv/openstore$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
6f15d9f3836c        openstore_api       "npm run dev"            13 minutes ago      Up 13 minutes       0.0.0.0:8080->8080/tcp     openstore_api_1
732cfa887041        mongo               "docker-entrypoint..."   13 minutes ago      Up 13 minutes       0.0.0.0:27017->27017/tcp   openstore_mongo_1
```

**Comment by bhdouglass** [comment]
The attach command isn't supposed to ever exit (unless you use CTRL+C). I'll give you the output of the running container, so you might not see anything unless you make a change and it reloads.
For the web container, it sounds like it crashed. Check it's out put by running `docker logs` (not sure if that's exactly it off the top of my head). Did you make sure to npm install for both the api and web?

**Comment by mardy** [comment]
I didn't run `npm install` or anything else: I'm just following the instructions here: https://github.com/UbuntuOpenStore/openstore-web/blob/master/README.md

**Comment by mardy** [comment]
Is there a way to populate the store? I created a smartfile account and created the config.json file with its keys, then logged in (via UbuntuOne), then tried to upload a click file, but I always get
```
There was an error creating your app, please try again later
```
I've also created a github application and wrote its keys in config.json (btw, as callback I used `http://local.open.uappexplorer.com/auth/github/callback`, is this correct?), but I believe that this is irrelevant, since I logged in via the Ubuntu account?

Also, one weird thing: it seems that I'm only "half" logged in: the site recognized my name, and let me get to the submission page. But if now I reload the page, I'm in a weird state where there's a "Log out" link (hinting that I'm logged in) but the "Submit" link now opens the "Rules for Submission" page, and not the actual upload page.

**Comment by bhdouglass** [comment]
Weird, apparently the npm install parts of the setup were removed. I've added them back so other can figure this out.

For the app not uploading check for any errors that happen if you run `attach_api` and then upload the click.

A Github app isn't necessary because you can easily log in with Ubuntu One without any setup, so you should be good there.

If you want to upload a new app you'll need to go to the "manage" tab and go from there. That submit link is just telling you how to do it and it's the same whether you are logged in or not.

**Comment by mardy** [comment]
I believe that this is working well now.
