### ISSUE TITLE
Assume software is proprietary when no license is specified

### ISSUE THREAD

**Issue by sverzegnassi** [UbuntuOpenStore/openstore-meta#172]
See "com.ubuntu.developer.1bsyl.cartes" for instance. When no license is specified by the app uploader, OpenStore does not force any default value and the related section in openstore-web appears empty.

Because of the primarily FOSS nature of the app store, we should safely presume that the app is proprietary.

Check following screenshot:

![screenshot from 2018-01-03 20-06-16](https://user-images.githubusercontent.com/1218443/34535281-cca66a54-f0c1-11e7-9f37-85cca57564b2.png)

**Comment by bhdouglass** [comment]
Fixed!
