### ISSUE TITLE
searching for apps from the same developer brings up too many results

### ISSUE THREAD

**Issue by balcy** [UbuntuOpenStore/openstore-meta#174]
If you search for other apps from the same developer using the open store app, it searches for apps containing the first name or the last name of the developer.

For example: more apps by Michael Stevens has all
 that contain "Michael" as result.

If the search is put in quotes, only apps containing the whole string are found. Of course it still could find apps, that contain that full name in the description, but the search is much more specific.

**Comment by balcy** [comment]
search right now:
![screenshot20180104_074631234](https://user-images.githubusercontent.com/848115/34553219-92e6ef0e-f126-11e7-84ea-818e4e333688.png)

**Comment by balcy** [comment]
quoted search:
![screenshot20180104_074739184](https://user-images.githubusercontent.com/848115/34553260-cbefbca4-f126-11e7-8796-355f79f802b7.png)

**Comment by sverzegnassi** [comment]
Hi, thanks for the report!

OpenStore in-app search is currently performed by our remote server, by using our old v1/apps endpoint. We're currently staging a new elastic search engine, which is already used by our web front-end and will be soon adopted by our UT app as well.

Could you please check whether [our website](https://open.uappexplorer.com) returns the results as expected?

**Comment by balcy** [comment]
ok thank you, on the website I get the right search result while I type, the only thing there is the search is reset (the page reloads) when you press enter after typing the search. Is that intended?

**Comment by bhdouglass** [comment]
The best way to search for a specific app author is to do it like this: https://open.uappexplorer.com/?sort=relevance&search=author%3ABrian%20Douglass
You should be able to use the `author:` prefix in the app as well.
The page reloading like that is a bug, do you mind filing another bug report about it?

**Comment by balcy** [comment]
ok I will open one.
I've tried author:"OTA-11" in the app and the result is "Bluetooth file transfer" because OTA-11 is in the description. (so in the app author: seems to be ignored.)

but once it works it would be good that a click on a button ("More from <xy>") would fill it with that syntax into the search input (see pic)

**Comment by balcy** [comment]
![screenshot20180105_181210279](https://user-images.githubusercontent.com/848115/34620040-6e60212c-f244-11e7-9d55-85c8d33a7d55.png)

**Comment by bhdouglass** [comment]
This has been fixed in the latest version of the OpenStore app!
