### ISSUE TITLE
Categories not translated

### ISSUE THREAD

**Issue by Anne017** [UbuntuOpenStore/openstore-meta#175]
The titles of the categories (Accessibility, Books & Comics, Business & Finance, etc.) are not translated in v2.12.
These strings are not available in Weblate and in the .pot file.

**Comment by bhdouglass** [comment]
Those are actually happen on the server/api side of things:
https://github.com/UbuntuOpenStore/openstore-api/blob/master/po/openstore-web.pot

But the weblate is still broken for the api, I'll have to bug them about it again.

**Comment by bhdouglass** [comment]
Ok, weblate is fixed now: https://translate.ubports.com/projects/openstore/openstore-api/
