### ISSUE TITLE
Updating the tags of an app also updates the last update date

### ISSUE THREAD

**Issue by kugiigi** [UbuntuOpenStore/openstore-meta#178]
Steps to reproduce:
1. Login to the OpenStore site.
2. Go to **Manage** and select an app.
3. Edit the **tags** fields (possibly other fields are affected as well)
4. **Save** the page.
5. Go to the page of the selected app from step 2 from the OpenStore app and/or site.
6. Check the field **Updated: (website) / Latest available version (app).**

**Comment by bhdouglass** [comment]
Fixed!
