### ISSUE TITLE
[Xenial] Openstore UI not usable.

### ISSUE THREAD

**Issue by ernesst** [UbuntuOpenStore/openstore-meta#179]
What happened: Openstore on xenial starts but doens't display any image, like if it was not connected to internet. 
However while browsing the website https://open.uappexplorer.com/ the app interpret the link and install any app. During installation no render is perfomed.

What I expected to happen: working like on vivid.

Logs
https://paste.ubuntu.com/26414896/

Versions:
SO: Ubuntu 16.04 (r208)
Openstore app: 2.13

**Comment by bhdouglass** [comment]
Is xenial even stable enough to the point it makes sense to test these things? And beside it's it using a different version of Qt, so we would have to recompile the app anyways. I'm going to close this for now. Feel free to open up the issue again when xenial is ready for app development.
