### ISSUE TITLE
[turbo] 16,04 openstore app doesn't show any app.

### ISSUE THREAD

**Issue by thehunchbacked** [UbuntuOpenStore/openstore-meta#180]
After fresh install of Xenial 16.04 on my Meizu Pro5 [turbo] (without wipe) the openstore app doesn't show content. I can see the menu with categories and the number of apps in each categorie. When selecting one categorie, it's empty.

This is the logfile from ~/.cache/upstart/application-click-openstore.openstor
---beginn
QHostInfo::lookupHost() called with no event dispatcher
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
qrc:///Main.qml:53: TypeError: Cannot read property 'length' of undefined
qrc:///DiscoverTab.qml:124: TypeError: Cannot read property 'installed' of null
qrc:///DiscoverTab.qml:119: TypeError: Cannot read property 'tagline' of null
qrc:///DiscoverTab.qml:114: TypeError: Cannot read property 'name' of null
qrc:///DiscoverTab.qml:114: TypeError: Cannot read property 'name' of null
qrc:///DiscoverTab.qml:119: TypeError: Cannot read property 'tagline' of null
qrc:///DiscoverTab.qml:124: TypeError: Cannot read property 'installed' of null
QString::arg: Argument missing: Keine Suchergebnisse., undefined
qrc:///Components/EmptyState.qml:40:5: QML Item: Binding loop detected for property "width"
QString::arg: Argument missing: Keine Suchergebnisse., undefined
qrc:///Components/EmptyState.qml:40:5: QML Item: Binding loop detected for property "width"
QObject::startTimer: Timers cannot be started from another thread
ubuntumirclient: Attempted to deliver an event to a non-existent window, ignoring.
*** Error in `openstore': munmap_chunk(): invalid pointer: 0x0005f868 ***
QHostInfo::lookupHost() called with no event dispatcher
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
qrc:///Main.qml:53: TypeError: Cannot read property 'length' of undefined
qrc:///DiscoverTab.qml:124: TypeError: Cannot read property 'installed' of null
qrc:///DiscoverTab.qml:119: TypeError: Cannot read property 'tagline' of null
qrc:///DiscoverTab.qml:114: TypeError: Cannot read property 'name' of null
qrc:///DiscoverTab.qml:114: TypeError: Cannot read property 'name' of null
qrc:///DiscoverTab.qml:119: TypeError: Cannot read property 'tagline' of null
qrc:///DiscoverTab.qml:124: TypeError: Cannot read property 'installed' of null
QString::arg: Argument missing: Keine Suchergebnisse., undefined
QObject::startTimer: Timers cannot be started from another thread
---end

**Comment by bhdouglass** [comment]
Unfortunately since 16.04 isn't really ready for app development and many things are still in a state of flux, the OpenStore doesn't support 16.04 yet. I'm going to close this for now, but once 16.04 becomes more stable for app development we can revisit the issue.
