### ISSUE TITLE
Broken search function 

### ISSUE THREAD

**Issue by TronFortyTwo** [UbuntuOpenStore/openstore-meta#182]
Using firefox on an android phone.

Steps to reproduce:
- open open.uappexplorer.com
- put some words in the search bar
- press enter

Expected result:
- the list of apps matching your keyword appears

real result
- the spinning circle appears
- the page quickly reloads
- the search bar is cleared
- no search has been performed

**Comment by bhdouglass** [comment]
I believe this is a duplicate of #176, so I'm going to close this one. If it is different please let me know.
