### ISSUE TITLE
openstore:// urls don't work properly when the app is not running

### ISSUE THREAD

**Issue by timsueberkrueb** [UbuntuOpenStore/openstore-meta#187]
Clicking `openstore://<app-id>` links should open Open Store and show the page for the app with `<app-id>`.
However, if the Open Store app is not already running, at least on my BQ Aquaris E4.5 (krillin) running 15.04 stable, this opens Open Store but not the specific app page.

**Comment by bhdouglass** [comment]
This has been fixed!

**Comment by timsueberkrueb** [comment]
Hooray, thank you :tada:
