### ISSUE TITLE
Certain apps are not «findable» in search but listen in categories

### ISSUE THREAD

**Issue by cibersheep** [UbuntuOpenStore/openstore-meta#188]
1) Open app in device (on web works fine)
2) Search for any of this terms «Beru», «beru», «ber» «ebook» «reader», «Schroll» (the author)
3) Beru (nor any app from Robert Schroll) is listed
4a) Tap on categies / Books and comics to find Beru
4b) Tap on categies / Utilities to find Browser Bookmarks

**Comment by cibersheep** [comment]
List is larger of apps not «findable» and not listen under search by author name
- tweakgeek
- wifiscanner
- RockWork

**Comment by bhdouglass** [comment]
Fixed! No app update needed.
