### ISSUE TITLE
Add architecture to app view

### ISSUE THREAD

**Issue by ismaelbonato** [UbuntuOpenStore/openstore-meta#190]
There is not exist any label about the app archtecture (only in the app name).

So it will be nice if OpenStore has the same feature than uappexplorer and maybe the other info labels too.

![image](https://user-images.githubusercontent.com/7233514/36940956-9f58158e-1f2e-11e8-823c-29766ebed279.png)

**Comment by bhdouglass** [comment]
Just pushed this!
