### ISSUE TITLE
Associate account w/ GitHub auth or Ubuntu auth

### ISSUE THREAD

**Issue by bittner** [UbuntuOpenStore/openstore-meta#191]
I'm logging in to https://open-store.io/ using my Ubuntu account. As there is an additional authentication option I'd like to make sure both option allow access to one and the same account (and no additional account is created).

As for what I can spot in the application (the website) there is no "account" that allows such a thing as associating emails (or authentication options in general) to an account when you're logged in. Also, I don't see any related routes [in the source code](https://github.com/UbuntuOpenStore/openstore-api/blob/master/src/app/auth.js).

Is associating an auth option to an existing account supported, or is support planned?

**Comment by bhdouglass** [comment]
As long as you use the same email address for both services you'll be logged into the same account. We don't (currently) have any plans to link accounts.

**Comment by bittner** [comment]
> As long as you use the same email address for both services

Which was the reason I asked. I do not, unfortunately.

**Comment by bhdouglass** [comment]
Gotcha, it might make sense to have an account linking feature at some point.
