### ISSUE TITLE
Automatically build packages for developers

### ISSUE THREAD

**Issue by UniversalSuperBox** [UbuntuOpenStore/openstore-meta#193]
Using the **power of Clickable**, it should be possible to enable the OpenStore to build Click packages for developers.

Having this option available would solve one huge problems for app developers, the need to rebuild and re-upload apps in case of ABI changes. It would also provide a bit of trust for users, knowing that the app is actually built from the listed source on the store page.

Ideal situation:
1. Create a new app with a Clickable template
1. Upload app to a hosted Git repository (Hopefully a service that has webhooks and integrations)
1. Log in to OpenStore, use an "Import from *service*"  option to create an app listing with most information pre-filled using the app manifest
1. OpenStore builds the click package from my repository and automatically uploads it (in the #141 future, to a development channel)

**Comment by bhdouglass** [comment]
I'm going to close this since clickable recently got much better at being part of a CI solution (ex: http://blog.bhdouglass.com/clickable/ubuntu-touch/2018/07/05/clickable-and-continuous-integration.html ) and got it's publish command.
