### ISSUE TITLE
Xenial 16.04 devel OpenStore app not rendering correctly

### ISSUE THREAD

**Issue by mebruno** [UbuntuOpenStore/openstore-meta#194]
Starting OpenStore on Xenial 16.04 devel  shows an empty page. Clicking in the empty space shows app info with install button. Click on install and the app will install as wanted. Making apps visible will be a step forwards?

**Comment by bhdouglass** [comment]
What version of the OpenStore app are you using?

**Comment by mebruno** [comment]
Cannot find version info. (rendering problem?)

It is standard in ubports 16.04 devel.

Suggestions how to find version number?



Op Ma, 12 maart, 2018 5:38 am schreef Brian Douglass:

**Comment by bhdouglass** [comment]
You can run `pkcon get-packages | grep openstore` from the command line to get the version. There might be another way, but I don't there there is any easy way to get that info from the GUI.

**Comment by bedna-KU** [comment]
I have same problem on Nexus 4, UBports 16.04.
OpenStore: trust-store-bin-2.0.1+ubports+0-20180216015428.7-1.gbpae0542.armhf

**Comment by mebruno** [comment]
openstore.openstore-team-2.15.armhfOp 12 mrt. 2018 22:00 schreef Brian Douglass <notifications@github.com>:You can run pkcon get-packages | grep openstore from the command line to get the version. There might be another way, but I don't there there is any easy way to get that info from the GUI.

**Comment by bhdouglass** [comment]
I was just informed by Marius that the correct version of the OpenStore for xenial is not yet in the images, so I'm going to close out this issue as you guys wait for the next update.

**Comment by mebruno** [comment]
I will wait..Thanks for the information.Op 13 mrt. 2018 18:03 schreef Brian Douglass <notifications@github.com>:I was just informed by Marius that the correct version of the OpenStore for xenial is not yet in the images, so I'm going to close out this issue as you guys wait for the next update.
