### ISSUE TITLE
Remove hass.io from your store

### ISSUE THREAD

**Issue by balloob** [UbuntuOpenStore/openstore-meta#196]
About listing https://open-store.io/app/hassio.hassio

I am the founder of Home Assistant and Hass.io. We did not give permission to use our name and logo. The author of Hass.io is definitely is not "Chaos delphin".

Please remove this listing as soon as possible.

**Comment by bhdouglass** [comment]
Thank you for reaching out to us about his issue. I have sent an email to both the author and maintainer of this app about your request. As far as I can tell this app is just a site specific browser around this link: `http://hassio:8123`.
So it sounds to me like if they get permission or stop using your trademakrs the app can continue to be included in the OpenStore (as the app equates to a browser). I hope that you and the author/maintainer can come to a mutually satisfactory agreement on this. In the meantime I have temporarily unlisted this app on the OpenStore.

**Comment by balloob** [comment]
My concern is exactly that it is just a link. I don't want people to think that they can install Home Assistant by installing this app, just to be disappointed. The odds of them trying another method will be slim and we have lost a user.

**Comment by bhdouglass** [comment]
To be clear, I have unlisted the webapp because it's my understanding that it is a violation of your trademark. Not because it is a link to your site. I invite you to discuss with the app author/maintainer about improving user experience or we would gladly accept an officially sanctioned app.

**Comment by Chaosdelphin** [comment]
I don't understand your problem. Of course, you cant control your hass.io without having it set up... You can also not control Kodi with your Phone without having it. Trying to install a HOMEautomation system on a MOBILE device might predestine you for a NOOB-award. 

So basically the idea behind sharing this app was:
-giving the ubtouch user which have hass.io at home the possibility to control their stuff. (maybe the hass.io project might offer such an app for the ubtouch platform.. this will be also great ;))
-Pushing the user which don't have hass.io installed at HOME to the hass.io project page. (this is why I added a link in the app description) so basically it's advertising for you

**Comment by balcy** [comment]
"and we have lost a user" ... I think you are just about to lose not only 1 open source enthusiast as (future) user
