### ISSUE TITLE
No icon for scopes

### ISSUE THREAD

**Issue by Gabriele69** [UbuntuOpenStore/openstore-meta#197]
The Openstore App "My App" not show Scopes icon.
See att. (Events, Calls[.
![photo_2018-05-03_17-15-29](https://user-images.githubusercontent.com/17642335/39585658-9c528b8e-4ef5-11e8-8124-78148f6e59b9.jpg)

**Comment by bhdouglass** [comment]
Thanks for bring this to our attention!

**Comment by bhdouglass** [comment]
Fixed in v2.43!
