### ISSUE TITLE
Nothing in Open Store... It's empty ??

### ISSUE THREAD

**Issue by TomRausner** [UbuntuOpenStore/openstore-meta#199]
Hi
I've noticed thru the last three or so updates that Open Store has been missing having any contents at all. From time to time I've seen same phenomenon on my Ubuntu desktop machine. Why is it happening and are there any connection between these two experiences of mine ?
Tom

**Comment by bhdouglass** [comment]
Are you running xenial on your phone?

**Comment by bhdouglass** [comment]
Are you still running into this issue?

**Comment by bhdouglass** [comment]
If you are still having issues, let me know and we can reopen this.
