### ISSUE TITLE
Cannot GET /about 

### ISSUE THREAD

**Issue by cibersheep** [UbuntuOpenStore/openstore-meta#201]
1) Type or click on link https://open-store.io/about
Message: Cannot GET /about

1) Go to https://open-store.io
2) Click on menu About
3) About page shows with no problem

![imatge](https://user-images.githubusercontent.com/6640041/40591739-ffb64b1e-6216-11e8-94eb-e98720b61e91.png)

**Comment by bhdouglass** [comment]
Fixed!
