### ISSUE TITLE
[open-store.io] enhance search function for xenial-compatibility

### ISSUE THREAD

**Issue by bastos77** [UbuntuOpenStore/openstore-meta#204]
I am looking forward to upgrade to xenial asap with my FP2. But I have no overview about the app compatibility to xenial.
A search possibility at least on the web view of OpenStore, only showing apps that are already on the right framework or compatible with xenial will be much appreciated.

**Comment by bhdouglass** [comment]
This should be pretty simple, thanks for the suggestion!

**Comment by bhdouglass** [comment]
Finished, check it out under the "more filters" button!

**Comment by bastos77** [comment]
Wow. Great! Thank you
