### ISSUE TITLE
App submission: no category selectable

### ISSUE THREAD

**Issue by Wend1go** [UbuntuOpenStore/openstore-meta#206]
On submitting a new App via the website there aren't any categories available in the combo box under "Discovery" -> "Category":

![openstore_categories_empty](https://user-images.githubusercontent.com/7413059/43037227-b05991fa-8d0b-11e8-84e4-686c0f96669c.png)

**Comment by bhdouglass** [comment]
Thanks for bringing this to my attention! I've corrected this so you should be good to go.

**Comment by Wend1go** [comment]
Its working now, thanks.
