### ISSUE TITLE
Navigation bar problem on https://open-store.io

### ISSUE THREAD

**Issue by iprudnik613** [UbuntuOpenStore/openstore-meta#207]
Hello!
I found that there are some problems on site  https://open-store.io with navigation bar. From page 6 it's doesn't work. "<" and ">" buttons are working, but pages and current page are not showing.
Navigation bar on page 5:
![screenshot_27-07-2018_10-00-15](https://user-images.githubusercontent.com/41670042/43299527-c4556242-9184-11e8-926c-a3ef2c7f5863.png)
For example, I typed page 23 in url:
![screenshot_27-07-2018_10-00-37](https://user-images.githubusercontent.com/41670042/43299528-c47c1cac-9184-11e8-99b2-209c3ef684d0.png)
And navigation bar doesn't show it:
![screenshot_27-07-2018_10-00-40](https://user-images.githubusercontent.com/41670042/43299529-c4a1fdc8-9184-11e8-90d3-a3e51aec944d.png)
Page 6:
![screenshot_27-07-2018_10-03-03](https://user-images.githubusercontent.com/41670042/43299530-c4c514ac-9184-11e8-9ea1-9eb500bffca3.png)
I tested it from FireFox and Chrome.

**Comment by bhdouglass** [comment]
Thanks for the heads up, I've been able to replicate this and I'll get it fixed soon!

**Comment by bhdouglass** [comment]
Just fix this!
