### ISSUE TITLE
Vivid apps still working on xenial

### ISSUE THREAD

**Issue by dcostan** [UbuntuOpenStore/openstore-meta#209]
In the store there are many apps built for vivid that are working also on xenial. I propose to insert a special system to tag vivid apps compatible with xenial, in order to expand available apps' range

**Comment by bhdouglass** [comment]
We did an automated process to migrate vivid apps to xenial a whie back (when we had a good idea they would work). Any apps left over either don't support xenial yet or their authors need to publish a xenial version. I would encourage you to reach out to app authors for them to upload a xenial version.

**Comment by dcostan** [comment]
I have just upgraded my BQ M10 to xenial and I noticed that there are some apps built for vivid that are working! So why do we need to throw them in the bin? The most of these are unfortunately unmaintained: this is the problemm

**Comment by bhdouglass** [comment]
Do you have specific examples? Most apps that we know to support xenial should already automatically have a xenial version.

**Comment by dcostan** [comment]
For Example Bluetooth file transfer (ubtd) from Michael Zanetti seems to work. Also AIDA64 is working (but unfortunately it is no mere present in the store, not migrated probably due to proprietary license)

**Comment by bhdouglass** [comment]
I just checked the code for ubtd, it has quite a bit of C++ in there that would need to be recompiled for xenial. I know some people have asked the AIDA64 developers to bring it to the OpenStore, but it unfortunately hasn't happened yet.
