### ISSUE TITLE
Cannot open click files from file manager

### ISSUE THREAD

**Issue by kugiigi** [UbuntuOpenStore/openstore-meta#210]
#Steps to reproduce
1. Open file manager
2. Select a click file to open

#Expected Result
OpenStore should be listed in content hub for apps capable of opening click files

#Actual Result
OpenStore is not listed in content hub

#Additional Information
Text files (.txt) shows OpenStore in the content hub. Opening though returns an error even of the opened file is an actual click file renamed to .txt

**Comment by bhdouglass** [comment]
Are you on xenial or vivid? I just tested this on xenial and it shows the OpenStore properly (fresh xenial install).

**Comment by bhdouglass** [comment]
@kugiigi I haven't been able to reproduce this on xenial, let me know which version you have

**Comment by kugiigi** [comment]
sorry for the late response...I forgot to reply LOL
anyway, yeah you are right, it does not happen in xenial
I guess you can close this one.
I forgot I'm still using vivid and xenial is the thing now 😅

**Comment by bhdouglass** [comment]
upgrade time ;)
