### ISSUE TITLE
whatsapp for Qt

### ISSUE THREAD

**Issue by tiocfaidharla** [UbuntuOpenStore/openstore-meta#213]
the above app flashes briefly (0.5sec) to whatsapp logo then closes. Nexus 5, 16.04stable. The other version of whatsappweb works for a time but needs all data cleared if, for example, you switch back to a pc instance of whatsappweb.

**Comment by bhdouglass** [comment]
Unfortunately it sounds like this is a problem with the whatsappweb app rather than the OpenStore so I'm closing this ticket. I would encourage you to reach out to the app's author with your problem: https://open-store.io/app/whatsappweb.nfsprodriver
