### ISSUE TITLE
Hide open button for the OpenStore app

### ISSUE THREAD

**Issue by mymike00** [UbuntuOpenStore/openstore-meta#216]
in the opestore app, there is an open button for each app, and also for the OpenStore app which has no sense as the openstore app is already opened. I suggest to hide that button
I can do it if it's not too difficult, I'll have to look into the code to find it...
![screenshot20181010_112059873](https://user-images.githubusercontent.com/28359593/46726825-70ca0200-cc7f-11e8-8e95-7d6ced7d81a5.png)

**Comment by bhdouglass** [comment]
That's a good suggestion, I'll leave this ticket to you if you want it!

**Comment by mymike00** [comment]
Yes please! I'll may ask you some hints if I'll have problems😁👍🏻

**Comment by bhdouglass** [comment]
Sounds good, just let me know if you need anything.

**Comment by bhdouglass** [comment]
Fixed by @mymike00 !

**Comment by mymike00** [comment]
Oh, I forgot the issue are in a separated repo, so I couldn't close the issue from tuesday pr😂
