### ISSUE TITLE
Move "open" button

### ISSUE THREAD

**Issue by bhdouglass** [UbuntuOpenStore/openstore-meta#41]
https://trello.com/c/7FXq2VOv/83-move-open-button

https://github.com/UbuntuOpenStore/openstore-app/issues/2

It would be nice to have the Open button for the installed apps, in the app view. Now it has to be scrolled all the way down to reach it.
![imatge](https://cloud.githubusercontent.com/assets/6640041/26178267/983cc502-3b5d-11e7-8c31-dec895cffe2b.png)

**Comment by mivoligo** [comment]
My idea is to put the "Open" button to the header as on the attached image.
![app-button-idea](https://user-images.githubusercontent.com/1629120/27049924-be3ac7cc-4fa8-11e7-89d6-cabd4fc2618e.png)

**Comment by sverzegnassi** [comment]
Fixed in v.2.00 (now merged into master)
